#!/bin/bash

# ARG_POSITIONAL_SINGLE([directory])
# ARGBASH_WRAP([simple],[filename])
# ARG_HELP([This program tells you size of files in a given directory in units you choose.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v1.4.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, know your rights: https://github.com/matejak/argbash

# THE DEFAULTS INITIALIZATION --- POSITIONALS
# THE DEFAULTS INITIALIZATION --- OPTIONALS
_ARG_UNIT="b"
_ARG_VERBOSE=off

# THE PRINT HELP FUNCION
print_help ()
{
	echo "This program tells you size of files in a given directory in units you choose."
	printf 'Usage: %s [-u|--unit <arg>] [--(no-)verbose] [-h|--help] <directory>\n' "$0"
	printf "\t-u,--unit: What unit we accept (b for bytes, k for kibibytes, M for mebibytes) (default: '%s')\n" "${_ARG_UNIT}"
	printf "\t-h,--help: Prints help\n"
}

# THE PARSING ITSELF
while test $# -gt 0
do
	_key="$1"
	case "$_key" in
		-u|--unit)
			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
			_ARG_UNIT="$2"
			_ARGS_SIMPLE_OPT+=("$1" "$2")
			shift
			;;
		--no-verbose|--verbose)
			_ARG_VERBOSE="on"
			_ARGS_SIMPLE_OPT+=("$1")
			test "${1:0:5}" = "--no-" && _ARG_VERBOSE="off"
			;;
		-h|--help)
			print_help
			exit 0
			;;
		*)
			_positionals+=("$1")
			;;
	esac
	shift
done

_positional_names=('_ARG_DIRECTORY' )
test ${#_positionals[@]} -lt 1 && { ( echo "FATAL ERROR: Not enough positional arguments --- we require exactly 1, but got only ${#_positionals[@]}."; print_help ) >&2; exit 1; }
test ${#_positionals[@]} -gt 1 && { ( echo "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')."; print_help ) >&2; exit 1; }
for (( ii = 0; ii < ${#_positionals[@]}; ii++))
do
	eval "${_positional_names[ii]}=\${_positionals[ii]}" || { echo "Error during argument parsing, possibly an Argbash bug." >&2; exit 1; }
done

# OTHER STUFF GENERATED BY Argbash
_ARGS_SIMPLE=("${_ARGS_SIMPLE_OPT[@]}" "${_ARGS_SIMPLE_POS[@]}")

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


test -f simple.sh || { echo "Missing the wrapped script, execute me from the directory where 'simple.sh' is."; exit 1; }
test -d "$_ARG_DIRECTORY" || { echo "We expected a directory, got '$_ARG_DIRECTORY'."; exit 1; }

for file in $_ARG_DIRECTORY/*
do
	test -f "$file" && echo "$file: $(./simple.sh "${_ARGS_SIMPLE_OPT[*]}" "$file")"
done

# ] <-- needed because of Argbash
