dnl And stop those annoying diversion warnings
m4_define([_m4_divert(STDOUT)], 1)
m4_define([ARGBASH],
[_MAKE_DEFAULTS
_MAKE_HELP
_MAKE_EVAL
[### END OF CODE GENERATED BY ARGBASH ###]
])
m4_divert_push([STDOUT])dnl
