dnl And stop those annoying diversion warnings
m4_define([_m4_divert(STDOUT)], 1)
dnl We wrap the generated stuff into m4_ignore, so when we re-run the script, the results will be +- the same. Devillish!
m4_define([ARGBASH_GO],
[[$0(FYI: Generated by version ]_ARGBASH_VERSION[)
# needed because of Argbash --> m4_ignore(@<:@]
_MAKE_DEFAULTS
_MAKE_HELP
_MAKE_EVAL
_MAKE_OTHER
# [@:>@ <-- needed because of Argbash])])dnl
m4_divert_push([STDOUT])dnl
