name: 'Execute tests'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install make autoconf dash

      - name: Install Argbash
        run: "sudo make install PREFIX=/usr"
        working-directory: ./resources

      - name: Test Argbash
        run: "make -B ../tests/regressiontests/Makefile && make check ARGBASH_EXEC=argbash ARGBASH_INIT_EXEC=argbash-init"
        working-directory: ./resources
